import { RESOURCES } from 'Utilities/constants';

import PATH from './path';

const TABS = [
  {
    label: 'Purchase Orders',
    url: PATH.PURCHASE_ORDER.URL,
    id: PATH.PURCHASE_ORDER.ID,
    main: true,
    icon: 'receipt',
    resource: [RESOURCES.PURCHASE_ORDER],
  },
  {
    label: 'Trips',
    url: PATH.TRIPS_LISTING.URL,
    id: PATH.TRIPS_LISTING.ID,
    main: true,
    icon: 'trips',
    isImageIcon: true,
    resource: [RESOURCES.TRIPS],
  },
  {
    label: 'DC Arrivals',
    url: PATH.DC_ARRIVALS.URL,
    id: PATH.DC_ARRIVALS.ID,
    main: true,
    icon: 'dcarrivals',
    resource: [RESOURCES.DC_ARRIVALS],
  },
  {
    label: 'SDN',
    url: PATH.SDN.URL,
    id: PATH.SDN.ID,
    main: true,
    icon: 'receipt',
    resource: [RESOURCES.SDN],
  },
  {
    label: 'Inventory',
    url: PATH.INVENTORY.URL,
    id: PATH.INVENTORY.ID,
    main: true,
    icon: 'inventory',
    resource: [],
  },
  {
    label: 'Inventory Consumption',
    url: PATH.INVENTORY_RECONCILIATION.URL,
    id: PATH.INVENTORY_RECONCILIATION.ID,
    main: true,
    icon: 'inventory',
    resource: [],
  },
  {
    label: 'Inventory Adjustment',
    url: PATH.INVENTORY_ADJUSTMENT.URL,
    id: PATH.INVENTORY_ADJUSTMENT.ID,
    main: true,
    icon: 'inventory',
    resource: [],
  },
  {
    label: 'Transfer Orders',
    url: PATH.TO_LISTING.URL,
    id: PATH.TO_LISTING.ID,
    main: true,
    icon: 'shipping',
    resource: [],
  },
  {
    label: '',
    url: PATH.ADD_MATERIAL_ASSIGNMENT.URL,
    id: PATH.ADD_MATERIAL_ASSIGNMENT.ID,
    main: false,
  },
  {
    label: '',
    url: PATH.EDIT_MATERIAL_ASSIGNMENT.URL,
    id: PATH.EDIT_MATERIAL_ASSIGNMENT.ID,
    main: false,
  },
  {
    label: '',
    url: PATH.RECEIVE_MATERIAL_ASSIGNMENT.URL,
    id: PATH.RECEIVE_MATERIAL_ASSIGNMENT.ID,
    main: false,
  },
  {
    label: '',
    url: PATH.DC_VENDOR_LEDGER.URL,
    id: PATH.DC_VENDOR_LEDGER.ID,
  },
  {
    label: '',
    url: PATH.MA_CUSTOMER_LEDGER.URL,
    id: PATH.MA_CUSTOMER_LEDGER.ID,
  },
  {
    label: '',
    url: PATH.ADD_MA_CUSTOMERS.URL,
    id: PATH.ADD_MA_CUSTOMERS.ID,
    main: false,
  },
  {
    label: '',
    url: PATH.ADD_MA_VENDORS.URL,
    id: PATH.ADD_MA_VENDORS.ID,
    main: false,
  },
  {
    label: '',
    url: PATH.EDIT_MA_VENDORS.URL,
    id: PATH.EDIT_MA_VENDORS.ID,
    main: false,
  },
  {
    label: '',
    url: PATH.ADJUST_MA_VENDORS.URL,
    id: PATH.ADJUST_MA_VENDORS.ID,
    main: false,
  },
  {
    label: '',
    url: PATH.ADJUST_MA_CUSTOMERS.URL,
    id: PATH.ADJUST_MA_CUSTOMERS.ID,
    main: false,
  },
  {
    label: '',
    url: PATH.RETURN_MA_VENDORS.URL,
    id: PATH.RETURN_MA_VENDORS.ID,
    main: false,
  },
  {
    label: '',
    url: PATH.RETURN_MA_CUSTOMERS.URL,
    id: PATH.RETURN_MA_CUSTOMERS.ID,
    main: false,
  },
  {
    label: '',
    url: PATH.CLONE_MA.URL,
    id: PATH.CLONE_MA.ID,
    main: false,
  },
  {
    label: 'Material Assignment',
    url: PATH.MATERIAL_ASSIGNMENT.URL,
    id: PATH.MATERIAL_ASSIGNMENT.ID,
    main: true,
    icon: 'salesorder',
    resource: [RESOURCES.MATERIAL_ASSIGNMENT],
    children: [
      {
        label: 'Mandi Farmers',
        url: PATH.VENDORS.URL,
        id: PATH.VENDORS.ID,
        icon: 'salesorder',
        resource: [],
      },
      {
        label: 'Vendors',
        url: PATH.DC_VENDORS.URL,
        id: PATH.DC_VENDORS.ID,
        icon: 'salesorder',
        resource: [],
      },
      {
        label: 'Customers',
        url: PATH.CUSTOMERS.URL,
        id: PATH.CUSTOMERS.ID,
        icon: 'salesorder',
        resource: [],
      },
    ],
  },
  {
    label: 'Payments',
    url: PATH.PAYMENTS.URL,
    id: PATH.PAYMENTS.ID,
    main: true,
    icon: 'salesorder',
    resource: [],
    children: [
      {
        label: 'My Payment Requests',
        url: PATH.MY_PAYMENT_REQUEST.URL,
        id: PATH.MY_PAYMENT_REQUEST.ID,
        icon: 'salesorder',
        resource: [],
      },
      {
        label: 'My Approval List',
        url: PATH.MY_APPROVAL_LIST.URL,
        id: PATH.MY_APPROVAL_LIST.ID,
        icon: 'salesorder',
        resource: [],
      },
    ],
  },
  {
    label: 'PO Approvals',
    url: PATH.PO_APPROVALS.URL,
    id: PATH.PO_APPROVALS.ID,
    main: true,
    icon: 'receipt',
    resource: [RESOURCES.PO_APPROVALS],
  },
  {
    label: '',
    url: PATH.ADD_TRIPS.URL,
    id: PATH.ADD_TRIPS.ID,
    main: false,
  },
  {
    label: '',
    url: PATH.EDIT_TRIPS.URL,
    id: PATH.EDIT_TRIPS.ID,
    main: false,
  },
  {
    label: '',
    url: PATH.PAYMENT_REQUEST_LISTING.URL,
    id: PATH.PAYMENT_REQUEST_LISTING.ID,
    main: false,
  },
  {
    label: '',
    url: PATH.ADD_PAYMENT_REQUEST.URL,
    id: PATH.ADD_PAYMENT_REQUEST.ID,
    main: false,
  },
  {
    label: '',
    url: PATH.EDIT_PAYMENT_REQUEST.URL,
    id: PATH.EDIT_PAYMENT_REQUEST.ID,
    main: false,
  },
  {
    label: '',
    url: PATH.ADD_BALANCE_PAYMENT_REQUEST.URL,
    id: PATH.ADD_BALANCE_PAYMENT_REQUEST.ID,
    main: false,
  },
  {
    label: '',
    url: PATH.EDIT_BALANCE_PAYMENT_REQUEST.URL,
    id: PATH.EDIT_BALANCE_PAYMENT_REQUEST.ID,
    main: false,
  },
  {
    label: '',
    url: PATH.ADD_TRIPS_WITH_TO.URL,
    id: PATH.ADD_TRIPS_WITH_TO.ID,
    main: false,
  },
  {
    label: '',
    url: PATH.PAYMENT_REQUEST_LISTING_FOR_PO.URL,
    id: PATH.PAYMENT_REQUEST_LISTING_FOR_PO.ID,
    main: false,
  },
  {
    label: 'Bill of Material',
    url: PATH.BOM.URL,
    id: PATH.BOM.ID,
    main: true,
    icon: 'receipt',
    resource: [RESOURCES.PACKAGING_BOM],
  },
  {
    label: 'Audit',
    url: PATH.AUDITS.URL,
    id: PATH.AUDITS.ID,
    main: true,
    icon: 'receipt',
    resource: [RESOURCES.INVENTORY_AUDIT],
  },
  {
    label: 'Audit Approval',
    url: PATH.AUDIT_APPROVAL.URL,
    id: PATH.AUDIT_APPROVAL.ID,
    main: true,
    icon: 'receipt',
    resource: [RESOURCES.INVENTORY_AUDIT_APPROVAL],
  },
  {
    label: '',
    url: PATH.INVENTORY_AUDIT_CREATE.URL,
    id: PATH.INVENTORY_AUDIT_CREATE.ID,
    main: false,
  },
  {
    label: '',
    url: PATH.INVENTORY_AUDIT_VIEW.URL,
    id: PATH.INVENTORY_AUDIT_VIEW.ID,
    main: false,
  },
  {
    label: '',
    url: PATH.INVENTORY_AUDIT_EDIT.URL,
    id: PATH.INVENTORY_AUDIT_EDIT.ID,
    main: false,
  },
  {
    label: '',
    url: PATH.INVENTORY_AUDIT_REVIEW.URL,
    id: PATH.INVENTORY_AUDIT_REVIEW.ID,
    main: false,
  },
];

export default TABS;
